version: "1"
root: .
main_path: "./pocketbase"
tmp_path: ./tmp
build_name: runner-build
build_args: ""
run_args: "serve"
build_log: runner-build-errors.log
valid_ext: .go, .tpl, .tmpl, .html
no_rebuild_ext: .tpl, .tmpl, .html
ignore: assets, tmp/*, app/**, node_modules/**
build_delay: "600"
colors: true
log_color_main: cyan
log_color_build: yellow
log_color_runner: green
log_color_watcher: magenta
log_color_app: ""
delve: false
delve_args: ""
debug: true
