version: '3'

services:
  pocketbase:
    build: .
    #volumes:
    #  - db:/pb_data/
    ports:
      - "8080:80"
    environment:
      - ADMIN_EMAIL=dev@mail.com
      - ADMIN_PASSWORD=HalloTest123!

#volumes:
#  db:
