version: '3'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - crt_domain=${CRT_DOMAIN}
    image: silentparty-event:${TAG}
    volumes:
     - db:/pb_data/
    ports:
      - "${PORT}:80"
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SMTP_SENDER_NAME=${SMTP_SENDER_NAME}
      - SMTP_SENDER_EMAIL=${SMTP_SENDER_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PW=${SMTP_PW}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET=${S3_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DEFAULT_GROUP=${BOT_DEFAULT_GROUP}
      - BOT_AWARENESS_GROUP=${BOT_AWARENESS_GROUP}
      - PARTYTIME=${PARTYTIME}

volumes:
 db:
